services:
  db:
    image: postgres:15
    container_name: restime_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: restime
      POSTGRES_USER: restuser
      POSTGRES_PASSWORD: nihad
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U restuser -d restime"]
      interval: 10s
      timeout: 5s
      retries: 5

  restime:
    build: .
    container_name: restime_app
    restart: on-failure
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: